"use client";

import Link from "next/link";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowLeft, FileText } from "lucide-react";
import AnimatedBackground from "@/components/ui/AnimatedBackground";

const sections = [
  { title: "1. Acceptance of Terms", body: "By accessing or using Financer, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the service." },
  { title: "2. Description of Service", body: "Financer is a personal finance tracking application that allows users to record income and expenses, view analytics, and receive AI-generated financial insights. The service is provided free of charge." },
  { title: "3. User Accounts", body: "You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate information when creating an account and to update your information as necessary. You are responsible for all activity that occurs under your account." },
  { title: "4. User Data", body: "You retain ownership of all financial data you enter into Financer. We do not sell, share, or distribute your personal financial data to third parties. Data is used solely to provide the service and generate AI insights for your account." },
  { title: "5. AI-Generated Insights", body: "Financial insights provided by Financer are generated by AI and are for informational purposes only. They do not constitute financial advice. You should consult a qualified financial advisor before making financial decisions based on any information provided by the service." },
  { title: "6. Acceptable Use", body: "You agree not to misuse the service, attempt to gain unauthorized access to any part of the system, or use the service for any illegal purpose. We reserve the right to suspend or terminate accounts that violate these terms." },
  { title: "7. Limitation of Liability", body: 'Financer is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the service, including but not limited to financial losses based on AI-generated insights.' },
  { title: "8. Changes to Terms", body: "We may update these terms from time to time. Continued use of the service after changes are posted constitutes acceptance of the updated terms. We will notify users of significant changes via the application." },
];

export default function TermsPage() {
  const prefersReduced = useReducedMotion();

  return (
    <div className="min-h-screen bg-[#060B18] text-slate-50 overflow-x-hidden">
      <AnimatedBackground />

      <div className="relative z-10 mx-auto max-w-4xl px-6 py-20">
        <motion.div initial={prefersReduced ? {} : { opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.4 }}>
          <Link href="/" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-slate-200 transition-colors mb-16 cursor-pointer">
            <ArrowLeft className="h-4 w-4" /> Back to home
          </Link>
        </motion.div>

        <motion.div initial={prefersReduced ? {} : { opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="mb-16">
          <div className="flex items-center gap-4 mb-4">
            <div className="rounded-xl bg-blue-500/10 p-3 border border-white/[0.06]">
              <FileText className="h-6 w-6 text-blue-400" />
            </div>
            <h1 className="text-5xl font-bold tracking-tight font-[family-name:var(--font-heading)]">Terms of Service</h1>
          </div>
          <p className="text-sm text-slate-500 mt-2">Last updated: June 23, 2026</p>
        </motion.div>

        <div className="space-y-6">
          {sections.map((s, i) => (
            <motion.div
              key={s.title}
              initial={prefersReduced ? {} : { opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.15 + i * 0.06 }}
              className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-7 backdrop-blur-sm hover:bg-white/[0.04] transition-colors duration-300"
            >
              <h2 className="text-lg font-semibold text-slate-100 font-[family-name:var(--font-heading)] mb-3">{s.title}</h2>
              <p className="text-slate-400 leading-relaxed text-[15px]">{s.body}</p>
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={prefersReduced ? {} : { opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.8 }}
          className="mt-16 pt-8 border-t border-white/[0.04] flex items-center justify-between"
        >
          <p className="text-sm text-slate-500">Questions? <span className="text-blue-400">legal@financer.app</span></p>
          <span className="text-xs text-slate-600">&copy; {new Date().getFullYear()} Financer</span>
        </motion.div>
      </div>
    </div>
  );
}
